type: "effort_controllers/JointGroupPositionController"
joints:
  - joint_1
  - joint_2
  - joint_3
  - joint_4
  - joint_5
  - joint_6
joint_1/pid: {p: 100, i: 100, d: 0.0}
joint_2/pid: {p: 100, i: 100, d: 0.0}
joint_3/pid: {p: 100, i: 100, d: 0.0}
joint_4/pid: {p: 100, i: 100, d: 0.0}
joint_5/pid: {p: 100, i: 100, d: 0.0}
joint_6/pid: {p: 100, i: 100, d: 0.0}


