% [load_data_IMU_MATRIX]: Read a file of type ".csv" generated by the MATRIX app.
%
% Syntax: 
%   [medicion] = load_data_IMU_MATRIX(file,idname)
% 
% Input parameters:
%   file-> file name
%   idname-> identifier of the sensor
%
% Output parameters:
%   medicion<- Read data
%
% Examples:
%   [TestMeasurements] = load_data_IMU_MATRIX('MeasurementsIMU_MATRIX_MATA1002195.csv',1000, 1030)
%

% History:
% Modified by Alejandro Castellanos Alonso on 2023/03/17

function [medicion] = load_data_IMU_MATRIX(filename, startRow, endRow)

DatosImportados = csv2cell(filename, 'fromfile');                           % Import data via the csv2cell function
%% Initialize variables
delimiter = '\t';                                                           % Data delimiter
if nargin <= 2                                                              % If the number of input parameters of the function is less than 2 --> DO:
    startRow = 2;                                                           % The initial row becomes number 2
    endRow = height(DatosImportados);                                       % The final row corresponds to the latest available data.
end                                                                         % End of sentence if-else

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
medicion.Date = DatosImportados(startRow:endRow, 1);                        % Date of measurement
medicion.Accel(:,1) = str2double(DatosImportados(startRow:endRow, 2));      % Accel_X
medicion.Accel(:,2) = str2double(DatosImportados(startRow:endRow, 3));      % Accel_Y
medicion.Accel(:,3) = str2double(DatosImportados(startRow:endRow, 4));      % Accel_Z
medicion.Gyro(:,1) = str2double(DatosImportados(startRow:endRow, 5));       % Gyro_X
medicion.Gyro(:,2) = str2double(DatosImportados(startRow:endRow, 6));       % Gyro_Y
medicion.Gyro(:,3) = str2double(DatosImportados(startRow:endRow, 7));       % Gyro_Z
medicion.bodySurfaceTemp = str2double(DatosImportados(startRow:endRow, 8)); % Body Surface Temperature
medicion.ambientTemp = str2double(DatosImportados(startRow:endRow, 9));     % Ambient Temperature
medicion.hr_raw = str2double(DatosImportados(startRow:endRow, 10));         % Raw Heart Rate
medicion.hr = str2double(DatosImportados(startRow:endRow, 11));             % Heart Rate
medicion.remarks = DatosImportados(startRow:endRow, 12);                    % Remarks
end                                                                         % End of the function load_data_IMU_MATRIX